// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuGcYyvaG_Je13EfEUZDPkBIBE4LzRwY',
    appId: '1:603659537268:web:540e1df95c03d0cd6dba21',
    messagingSenderId: '603659537268',
    projectId: 'thesisapp-e1677',
    authDomain: 'thesisapp-e1677.firebaseapp.com',
    databaseURL: 'https://thesisapp-e1677-default-rtdb.firebaseio.com',
    storageBucket: 'thesisapp-e1677.firebasestorage.app',
    measurementId: 'G-7D0XQM174V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpIv94ucc6L8D9sdYcV40N3FYRrjHbRM0',
    appId: '1:603659537268:android:6d377faacf01a7f76dba21',
    messagingSenderId: '603659537268',
    projectId: 'thesisapp-e1677',
    databaseURL: 'https://thesisapp-e1677-default-rtdb.firebaseio.com',
    storageBucket: 'thesisapp-e1677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQt1bwkRrPrIfiaw3krZnzabf71a7b7A',
    appId: '1:603659537268:ios:169c2ae100f145a56dba21',
    messagingSenderId: '603659537268',
    projectId: 'thesisapp-e1677',
    databaseURL: 'https://thesisapp-e1677-default-rtdb.firebaseio.com',
    storageBucket: 'thesisapp-e1677.firebasestorage.app',
    iosClientId: '603659537268-e5ap9ejm88fm8rhgi9bmkaqv1b0tib8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQt1bwkRrPrIfiaw3krZnzabf71a7b7A',
    appId: '1:603659537268:ios:169c2ae100f145a56dba21',
    messagingSenderId: '603659537268',
    projectId: 'thesisapp-e1677',
    databaseURL: 'https://thesisapp-e1677-default-rtdb.firebaseio.com',
    storageBucket: 'thesisapp-e1677.firebasestorage.app',
    iosClientId: '603659537268-e5ap9ejm88fm8rhgi9bmkaqv1b0tib8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyuGcYyvaG_Je13EfEUZDPkBIBE4LzRwY',
    appId: '1:603659537268:web:44bb73c73ea04cf36dba21',
    messagingSenderId: '603659537268',
    projectId: 'thesisapp-e1677',
    authDomain: 'thesisapp-e1677.firebaseapp.com',
    databaseURL: 'https://thesisapp-e1677-default-rtdb.firebaseio.com',
    storageBucket: 'thesisapp-e1677.firebasestorage.app',
    measurementId: 'G-TVRKBN4K4C',
  );
}
